pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
		        sh 'gradle-java-at08/gradlew clean build -p gradle-java-at08'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
				sh 'gradle-java-at08/gradlew test -p gradle-java-at08'
                sh 'gradle-java-at08/gradlew check -p gradle-java-at08'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'gradle-java-at08/build/libs/**/*.jar', fingerprint: true
            archiveArtifacts artifacts: 'gradle-java-at08/build/libs/**/*.war', fingerprint: true
            junit 'gradle-java-at08/build/test-results/**/*.xml'
        }
    }
}
